# Applying Neural Network for different Logic Gates

## First let's apply for AND Gate

### Importing necessary libraries

In [2]:
import matplotlib.pyplot as plt
import numpy as np

### Assigning different Input values

In [3]:
# Assign Input values
feature_one = np.array([[0,0], [0,1], [1,0], [1,1]])
print(feature_one.shape)
feature_one

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

### Assigning Target output as per the Truth Table for AND gate

### Boolean Expression -- A*B -- Target outputs

### (0,1) - 0
### (0,0) - 0
### (1,0) - 0
### (1,1) - 1

In [4]:
# Target output
target_output = np.array([[0,0,0,1]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [0],
       [0],
       [1]])

### Assigning random weights

In [22]:
# Assign the weights
weights = np.array([[12.5053271],[12.5053271]]) 
print(weights.shape)
weights

(2, 1)


array([[12.5053271],
       [12.5053271]])

### Adding Bias value ( if needed - as per the input value )

### Also assigning Standard Learning Rate

In [23]:
#Adding Bias values and Assigning a Learning rate
#bias weight
bias = -19.04631113 
#neural network

lr = 0.05 # Standard Rate

### Using Sigmoid Function for converting the value in the range of (0,1)
### Sigmoid Function serves as an activation function in our neural network training.

In [16]:
# Derivative of sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))


### Following is the logic for applying FeedForward and Backpropagation to get the target output.

### Epoch - Generally indicates the number of passes of the entire training dataset the machine learning algorithm has completed


In [24]:
# The main logic for predicting output and updating the weight values:

for epoch in range(10000):
    inputs = feature_one

    # feedforward input
    in_o = np.dot(feature_one, weights) + bias

    #feedforward output
    out_o = sigmoid(in_o)


    # backpropagation calculating error
    error = out_o - target_output

    # applying formula
    print(error.sum())

# Calculating derivative
    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    # Multiplying individual derivatives
    deriv = derror_douto * douto_dino

    # Multiplying with the 3rd individual derivative
    # finding the transpose of input features
    inputs = feature_one.T
    deriv_final=np.dot(inputs,deriv)
    
    #updating the weight values
    weights -= lr * deriv_final

    # updating the bias weight value
    for i in deriv:
        bias -= lr * i


0.000319831963435652
0.0003198308020076878
0.00031982964058809016
0.000319828479176624
0.0003198273177738766
0.0003198261563793813
0.0003198249949932395
0.0003198238336157987
0.00031982267224649804
0.0003198215108859079
0.0003198203495335464
0.0003198191881895519
0.00031981802685402327
0.00031981686552719213
0.00031981570420850335
0.00031981454289816726
0.00031981338159630616
0.00031981222030311434
0.00031981105901817374
0.00031980989774159016
0.00031980873647347724
0.000319807575213933
0.00031980641396262173
0.00031980525271967444
0.0003198040914851926
0.00031980293025937094
0.00031980176904169034
0.0003198006078324522
0.0003197994466318031
0.00031979828543949457
0.00031979712425564324
0.00031979596308002534
0.0003197948019130637
0.00031979364075435633
0.00031979247960421415
0.00031979131846240905
0.00031979015732915743
0.0003197889962040161
0.00031978783508744297
0.00031978667397932576
0.00031978551287966056
0.00031978435178853064
0.00031978319070563414
0.00031978202963108167
0.00031

### Now we get the Updated values of Weights and bias to achieve the target output

In [25]:
# Updated values of weights and bias as per the calculations
print(weights)
print(bias)

[[12.57611078]
 [12.57611078]]
[-19.1524876]


### Finally, we assign the input values and getting the target output one by one for each & every input. 

In [34]:
#taking input
#pt=np.array([0,1]) 
pt=np.array([1,1])
# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result

print(result2)
print("Rounding off - ", round(result2[0]))
print("Close to 1 - which is our target output for [1,1]")

[0.99752672]
Rounding off -  1.0
Close to 1 - which is our target output for [1,1]


## As we can see if we keep Updating the values for weights and bias, we can get our target output 

# Similarly, Let's apply the same for NOR Gate

In [43]:
# Importing necessary libraries
import matplotlib.pyplot as plt
import numpy as np

In [44]:
# Assign Input values
feature_two = np.array([[0,0], [0,1], [1,0], [1,1]])
print(feature_two.shape)
feature_two

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

## Assigning Target output as per the Truth Table for NOR gate


## Boolean Expression -- (A+B)^Transpose -- Target outputs

## (0,0) - 1
## (0,1) - 0
## (1,0) - 0
## (1,1) - 0

In [45]:
# Target output
target_output = np.array([[1,0,0,0]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output


(4, 1)


array([[1],
       [0],
       [0],
       [0]])

### Assigning Random weights 

In [46]:
# Assign the weights ( random )
weights = np.array([[8.348],[8.348]])
print(weights.shape)
weights


(2, 1)


array([[8.348],
       [8.348]])

In [47]:
#Adding Bias values and Assigning a Learning rate
bias = 3.592
#neural network

# Standard Learning Rate
lr = 0.05

In [48]:
# Derivative of sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))


### Sometimes we can increase the Number of Epochs for Better Results

In [49]:
# The main logic for predicting output and updating the weight values:

for epoch in range(30000):
    inputs = feature_two

    # feedforward input
    in_o = np.dot(feature_two, weights) + bias

    #feedforward output
    out_o = sigmoid(in_o)


    # backpropagation calculating error
    error = out_o - target_output

    # applying formula
    print(error.sum())

# Calculating derivative
    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    # Multiplying individual derivatives
    deriv = derror_douto * douto_dino

    # Multiplying with the 3rd individual derivative
    # finding the transpose of input features
    inputs = feature_two.T
    deriv_final=np.dot(inputs,deriv)
    
    #updating the weight values
    weights -= lr * deriv_final

    # updating the bias weight value
    for i in deriv:
        bias -= lr * i


2.9731820536498774
2.97240839082078
2.9716132677561817
2.97079613911747
2.9699564486000973
2.9690936288846737
2.968207101599716
2.967296277296904
2.966360555439711
2.965399324406311
2.9644119615077047
2.9633978330220314
2.9623562942460606
2.9612866895649006
2.9601883525409782
2.9590606060233755
2.957902762278637
2.9567141231441845
2.955493980205505
2.954241614998284
2.9529562992366873
2.951637295069009
2.950283855361903
2.9488952240144393
2.9474706363032155
2.9460093192597645
2.944510492081493
2.942973366577364
2.9413971476495306
2.939781033812109
2.938124217748234
2.936425886906515
2.934685224137973
2.93290140837446
2.9310736153495416
2.929201018362708
2.9272827890877373
2.9253180984259286
2.9233061174048123
2.9212460181228592
2.9191369747405678
2.9169781645181745
2.9147687689001116
2.9125079746461386
2.9101949750089515
2.9078289709578433
2.905409172447836
2.902934799733476
2.900405084726271
2.897819272394517
2.895176622204029
2.8924764095980255
2.8897179275141642
2.886900487936452
2.

In [50]:
print(weights)
print(bias)


[[-9.21362736]
 [-9.21362736]]
[4.0262515]


In [52]:
#taking input

pt=np.array([0,1])
# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)
print("Rounding off - ", round(result2[0]))
print("Close to 0 - which is our Target output for [0,1]")

[0.00555561]
Rounding off -  0.0
Close to 0 - which is our Target output for [0,1]
